name: Deploy to Amazon EC2 

on:
  push:
    branches: 
      - master

env:
  EC2_DOMAIN_NAME : "ec2-18-196-55-0.eu-central-1.compute.amazonaws.com"
  AWS_REGION_NAME : "eu-central-1b"
  AWS_S3_BUCKET_NAME : "aliaksei.sab"

jobs:
  deplyment:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: git clone our repo
      uses: actions/checkout@v1
    
     

      

    - name: Clone a remote repo
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa 
        scp -i ~/.ssh/id_rsa -r . ubuntu@${{ env.EC2_DOMAIN_NAME }}:~/
      
        
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}
