name: Deploy to Amazon EC2 

on:
  push:
    branches: 
      - master

env:
  EC2_DOMAIN_NAME : "ec2-18-196-55-0.eu-central-1.compute.amazonaws.com"
  AWS_REGION_NAME : "eu-central-1b"
  AWS_S3_BUCKET_NAME : "aliaksei.sab"

jobs:
  deplyment:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: git clone our repo
      uses: actions/checkout@v1
    
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.EC2_DOMAIN_NAME }}
        REMOTE_USER: ubuntu


      

#     - name: Clone a remote repo
#       run: |
#         mkdir ~/.ssh
#         echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2.pem
#         chmod 400 ~/.ssh/ec2.pem
#         scp -i ~/.ssh/ec2.pem -r . ubuntu@${{ env.EC2_DOMAIN_NAME }}:~/
      
        
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}
